[build]
  publish = "build/web"
  command = """
    if [ ! -d "flutter" ]; then
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter
    fi &&
    export PATH="$PATH:$(pwd)/flutter/bin" &&
    flutter doctor &&
    flutter pub get &&
    flutter build web --release
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  FLUTTER_WEB = "true"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
