[build]
  publish = "build/web"
  command = """
    echo "🔄 Checking for Flutter SDK..." &&
    if [ ! -d "flutter" ]; then
      echo "📥 Cloning Flutter SDK..."
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter
    fi &&
    export PATH="$PATH:$(pwd)/flutter/bin" &&
    echo "🩺 Running flutter doctor..." &&
    flutter doctor || true &&
    echo "📦 Getting dependencies..." &&
    flutter pub get &&
    echo "🚧 Building Flutter Web app..." &&
    flutter build web --release
  """


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  FLUTTER_WEB = "true"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
