name: miniapp_web
description: "A Flutter web project with Tetris game."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Game dependencies
  flutter_localizations:
    sdk: flutter
  overlay_support: ^2.1.0
  vector_math: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets for the game
  assets:
    - assets/material.png
    - assets/audios/
    - assets/alipay.jpg
    - assets/wechat.png
